### ISSUE TITLE
Migrate tut to mdoc

### ISSUE THREAD

**Issue by paualarco** [monix/monix.io#96]
At some point would be needed to migrate from [tut](https://github.com/tpolecat/tut) to [mdoc](https://scalameta.org/mdoc/) since it has been deprecated.

**Comment by alexandru** [comment]
Yeah, but somebody has to do it 🙂

I've added a custom tut integration, because I wanted to support multiple versions and it was nice being able to have articles with dependencies and their versions specified in the header.

Copied the integration code from https://github.com/typelevel/typelevel.github.com/

**Comment by alexandru** [comment]
Of course, I may have overestimated the need to specify custom versions. 2x documents for example could be declared final, as we no longer edit them, there's no need to have them type checked every time.

**Comment by paualarco** [comment]
Hey @alexandru,
Just raised it in case it was something you hadn't realised... but I supposed you were aware already.
Not sure how much work that would be... I guess that if typelevel still has not migrated it can wait too.
